<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="smaCoViLanguage" nsURI="http://www.example.org/smaCoViLanguage"
    nsPrefix="smaCoViLanguage">
  <eClassifiers xsi:type="ecore:EClass" name="SmartContract" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Term" eSuperTypes="#//SmartContract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="smartcontract" upperBound="-1"
        eType="#//SmartContract" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orelse" upperBound="-1"
        eType="#//OrElse" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Adico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AttributeName" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deontic" eSuperTypes="#//Adico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Deontic" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Adico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operator" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstPartCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastConditionPart" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Aim" eSuperTypes="#//Adico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Aim" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AimObject" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Targets" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrElse" eSuperTypes="#//Term">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Consequence" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Adico" abstract="true" eSuperTypes="#//SmartContract"/>
  <eClassifiers xsi:type="ecore:EClass" name="Main" eSuperTypes="#//SmartContract">
    <eStructuralFeatures xsi:type="ecore:EReference" name="smartcontract" upperBound="-1"
        eType="#//SmartContract" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Adico"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleCondition" eSuperTypes="#//Adico">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operator" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstPartCondition" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
</ecore:EPackage>
